apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
      - name: spring-boot-k8s
        image: ricardosanfelice/kubernetes_app # Image that will be used to containers in the cluster
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          request:
            cpu: 150m
            memory: 200Mi
        # imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080 # The port that the container is running on in the cluster
        env:
        - name: MY_POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
         