apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
- name: ricardosanfelice/kubernetes_app
  newTag: 0.0.2-SNAPSHOT

replicas:
- count: 1
  name: kubernetes_app

patchesStrategicMerge:
  - deployment-patch.yaml