apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ricardosanfelice/kubernetes_app
  newTag: master_76486dfc89c8c12c4d23b0ea50149fce3a4f2395

replicas:
- count: 1
  name: spring-boot-k8s

patchesStrategicMerge:
- deployment-patch.yaml
