apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ricardosanfelice/kubernetes_app
  newTag: master_b62c81231dd14ce8cdc380895756ae9945f481c5

replicas:
- count: 1
  name: spring-boot-k8s

patchesStrategicMerge:
- deployment-patch.yaml
