apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ricardosanfelice/kubernetes_app
  newTag: master_cc99035906a362c3fd3ea187c6722b56b9ec57b5

replicas:
- count: 1
  name: spring-boot-k8s

patchesStrategicMerge:
- deployment-patch.yaml
