apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ricardosanfelice/kubernetes_app
  newTag: master_b09c4b73fbe400f4ae945ecd3245882633d3c27c

replicas:
- count: 1
  name: spring-boot-k8s

patchesStrategicMerge:
- deployment-patch.yaml
