apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
  namespace: qa
spec:
  template:
    spec:
      containers:
      - name: spring-boot-k8s
        env:
          - name: ENV_NAME
            value: "QA"