name: image_deploy
on: 
  workflow_dispatch:
    inputs:
      app:
        description: 'Application name'
        required: true
      image:
        description: 'Image to deploy'
        required: true        
      environment:
        description: 'Environment to deploy'
        type: choice
        required: true
        options:
        - dev
        - prod
        - qa
jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
      - name: Update image
        run: |
          cd "applications/${{ inputs.app }}/${{ inputs.environment }}"
          kustomize edit set image ${{ inputs.image }}
          git add .
          git commit -m "Set ${{ inputs.app }} image tag to ${{ inputs.image }} in ${{ inputs.environment }} environment"
          git push
